version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "sunday"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"